postgres1:
  image: danielhood/postgres1
  links:
    - postgres-users:postgres
  ports:
    - "8080:8080"

postgres-users:
  image: danielhood/postgres-users
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
